sudo: required
dist: trusty
python:
    - "3.6"
branches:
  only:
  - master  
before_install:
- wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
- bash miniconda.sh -b -p ~/install
install:
- export PATH=~/install/bin/:$PATH
- conda install --yes -c conda-forge -c bioconda -q nextflow salmon fastqc multiqc
script:
- nextflow run paired.nf
